In [1]:
import pandas as pd
import sqlite3

In [2]:
# read csv
df = pd.read_csv('sales_data_sample.csv',encoding='latin1')

In [3]:
conn = sqlite3.connect(':memory:')
df.to_sql('sales', conn, index=False, if_exists='replace')

print('Data Load Ho Gaya')
print(df.columns.tolist())  #column ka name dekhne ke liye

Data Load Ho Gaya
['ORDERNUMBER', 'QUANTITYORDERED', 'PRICEEACH', 'ORDERLINENUMBER', 'SALES', 'ORDERDATE', 'STATUS', 'QTR_ID', 'MONTH_ID', 'YEAR_ID', 'PRODUCTLINE', 'MSRP', 'PRODUCTCODE', 'CUSTOMERNAME', 'PHONE', 'ADDRESSLINE1', 'ADDRESSLINE2', 'CITY', 'STATE', 'POSTALCODE', 'COUNTRY', 'TERRITORY', 'CONTACTLASTNAME', 'CONTACTFIRSTNAME', 'DEALSIZE']

In [4]:
query = "SELECT * FROM sales LIMIT 5;"
pd.read_sql(query, conn)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,None,NYC,NY,10022,USA,None,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,None,Reims,None,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,None,Paris,None,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,None,Pasadena,CA,90003,USA,None,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,None,San Francisco,CA,None,USA,None,Brown,Julie,Medium

In [5]:
query = "SELECT DISTINCT PRODUCTLINE FROM sales;"
pd.read_sql(query, conn)

        PRODUCTLINE
0       Motorcycles
1      Classic Cars
2  Trucks and Buses
3      Vintage Cars
4            Planes
5             Ships
6            Trains

## == har product ka total sales ==

In [6]:
query = "SELECT PRODUCTLINE, SUM(SALES) AS total_sales FROM sales GROUP BY PRODUCTLINE ORDER BY total_sales DESC;"
pd.read_sql(query, conn)

        PRODUCTLINE  total_sales
0      Classic Cars   3919615.66
1      Vintage Cars   1903150.84
2       Motorcycles   1166388.34
3  Trucks and Buses   1127789.84
4            Planes    975003.57
5             Ships    714437.13
6            Trains    226243.47

## == country bise order ==

In [7]:
query = "SELECT COUNTRY, COUNT(*) AS total_orders FROM sales GROUP BY COUNTRY ORDER BY total_orders DESC;"
pd.read_sql(query, conn)

        COUNTRY  total_orders
0           USA          1004
1         Spain           342
2        France           314
3     Australia           185
4            UK           144
5         Italy           113
6       Finland            92
7        Norway            85
8     Singapore            79
9        Canada            70
10      Denmark            63
11      Germany            62
12       Sweden            57
13      Austria            55
14        Japan            52
15      Belgium            33
16  Switzerland            31
17  Philippines            26
18      Ireland            16

## == top 5 highest sales bale order ==

In [8]:
query = "SELECT ORDERNUMBER, PRODUCTLINE, SALES FROM sales ORDER BY SALES DESC LIMIT 5;"
pd.read_sql(query, conn)

   ORDERNUMBER   PRODUCTLINE    SALES
0        10407  Vintage Cars  14082.8
1        10322  Vintage Cars  12536.5
2        10424  Classic Cars  12001.0
3        10412  Classic Cars  11887.8
4        10403   Motorcycles  11886.6

## == year bise total_sales ==

In [9]:
query = "SELECT YEAR_ID, SUM(SALES) AS total_sales FROM sales GROUP BY YEAR_ID ORDER BY YEAR_ID;"
pd.read_sql(query, conn)

   YEAR_ID  total_sales
0     2003   3516979.54
1     2004   4724162.60
2     2005   1791486.71

## == product jinka total 500000 se jyada ==

In [10]:
query = "SELECT PRODUCTLINE, SUM(SALES) AS total_sales FROM sales GROUP BY PRODUCTLINE HAVING SUM(SALES) > 500000;"
pd.read_sql(query, conn)

        PRODUCTLINE  total_sales
0      Classic Cars   3919615.66
1       Motorcycles   1166388.34
2            Planes    975003.57
3             Ships    714437.13
4  Trucks and Buses   1127789.84
5      Vintage Cars   1903150.84

## == cancelled order ==

In [11]:
query = "SELECT COUNT(*) AS cancelled_orders FROM sales WHERE STATUS = 'Cancelled';"
pd.read_sql(query, conn)

   cancelled_orders
0                60

## == har country ka total sale ==

In [12]:
query  = "SELECT COUNTRY, SUM(SALES) AS total_sales FROM sales GROUP BY COUNTRY ORDER BY total_sales DESC;"
pd.read_sql(query, conn)

        COUNTRY  total_sales
0           USA   3627982.83
1         Spain   1215686.92
2        France   1110916.52
3     Australia    630623.10
4            UK    478880.46
5         Italy    374674.31
6       Finland    329581.91
7        Norway    307463.70
8     Singapore    288488.41
9       Denmark    245637.15
10       Canada    224078.56
11      Germany    220472.09
12       Sweden    210014.21
13      Austria    202062.53
14        Japan    188167.81
15  Switzerland    117713.56
16      Belgium    108412.62
17  Philippines     94015.73
18      Ireland     57756.43

## == shiped order count ==

In [13]:
query = "SELECT COUNT(*) AS shipped_order FROM sales WHERE STATUS = 'Shipped';"
pd.read_sql(query, conn)

   shipped_order
0           2617

## == har product ka avg quantity ==

In [14]:
query = "SELECT PRODUCTLINE, AVG(QUANTITYORDERED) AS avg_qty FROM sales GROUP BY PRODUCTLINE"
pd.read_sql(query, conn)

        PRODUCTLINE    avg_qty
0      Classic Cars  35.152017
1       Motorcycles  35.235650
2            Planes  35.055556
3             Ships  34.730769
4            Trains  35.220779
5  Trucks and Buses  35.803987
6      Vintage Cars  34.710049

## == AND condition - USA + large deals ==

In [15]:
query = "SELECT * FROM sales WHERE COUNTRY ='USA' AND DEALSIZE ='Large';"
pd.read_sql(query, conn)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10140,37,100.00,11,7374.10,7/24/2003 0:00,Shipped,3,7,2003,...,9408 Furth Circle,None,Burlingame,CA,94217,USA,None,Hirano,Juri,Large
1,10312,48,100.00,3,11623.70,10/21/2004 0:00,Shipped,4,10,2004,...,5677 Strong St.,None,San Rafael,CA,97562,USA,None,Nelson,Valarie,Large
2,10381,36,100.00,3,8254.80,2/17/2005 0:00,Shipped,1,2,2005,...,7734 Strong St.,None,San Francisco,CA,None,USA,None,Brown,Julie,Large
3,10201,49,100.00,4,8065.89,12/1/2003 0:00,Shipped,4,12,2003,...,5557 North Pendale Street,None,San Francisco,CA,None,USA,None,Murphy,Julie,Large
4,10237,39,100.00,9,7023.90,4/5/2004 0:00,Shipped,2,4,2004,...,2678 Kingston Rd.,Suite 101,NYC,NY,10022,USA,None,Frick,Michael,Large
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59,10388,46,100.00,2,10066.60,3/3/2005 0:00,Shipped,1,3,2005,...,1785 First Street,None,New Bedford,MA,50553,USA,None,Benitez,Violeta,Large
60,10401,85,88.75,10,7543.75,4/3/2005 0:00,On Hold,2,4,2005,...,7476 Moss Rd.,None,Newark,NJ,94019,USA,None,Brown,William,Large
61,10318,50,100.00,8,7119.00,11/2/2004 0:00,Shipped,4,11,2004,...,7586 Pompton St.,None,Allentown,PA,70267,USA,None,Yu,Kyung,Large
62,10388,50,100.00,3,7154.50,3/3/2005 0:00,Shipped,1,3,2005,...,1785 First Street,None,New Bedford,MA,50553,USA,None,Benitez,Violeta,Large
63,10401,77,92.00,9,7084.00,4/3/2005 0:00,On Hold,2,4,2005,...,7476 Moss Rd.,None,Newark,NJ,94019,USA,None,Brown,William,Large

## == sales > 5000 , quantityorders > 40 ==

In [16]:
query = "SELECT * FROM sales WHERE SALES > 5000 OR QUANTITYORDERED > 40;"
pd.read_sql(query, conn)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,None,Paris,None,75508,France,EMEA,Da Cunha,Daniel,Medium
1,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,None,Pasadena,CA,90003,USA,None,Young,Julie,Medium
2,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,None,San Francisco,CA,None,USA,None,Brown,Julie,Medium
3,10188,48,100.00,1,5512.32,11/18/2003 0:00,Shipped,4,11,2003,...,"Drammen 121, PR 744 Sentrum",None,Bergen,None,N 5804,Norway,EMEA,Oeztan,Veysel,Medium
4,10211,41,100.00,14,4708.44,1/15/2004 0:00,Shipped,1,1,2004,...,"25, rue Lauriston",None,Paris,None,75016,France,EMEA,Perrier,Dominique,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089,10197,42,50.23,12,2109.66,11/26/2003 0:00,Shipped,4,11,2003,...,"Rambla de Catalu¤a, 23",None,Barcelona,None,8022,Spain,EMEA,Saavedra,Eduardo,Small
1090,10208,42,63.88,6,2682.96,1/2/2004 0:00,Shipped,1,1,2004,...,"2, rue du Commerce",None,Lyon,None,69004,France,EMEA,Saveley,Mary,Small
1091,10337,42,97.16,5,4080.72,11/21/2004 0:00,Shipped,4,11,2004,...,5905 Pompton St.,Suite 750,NYC,NY,10022,USA,None,Hernandez,Maria,Medium
1092,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",None,Madrid,None,28034,Spain,EMEA,Freyre,Diego,Medium
1093,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,None,Boston,MA,51003,USA,None,Yoshido,Juri,Medium

## == sari unique country ==

In [17]:
query = "SELECT DISTINCT COUNTRY FROM sales"
pd.read_sql(query, conn)

        COUNTRY
0           USA
1        France
2        Norway
3     Australia
4       Finland
5       Austria
6            UK
7         Spain
8        Sweden
9     Singapore
10       Canada
11        Japan
12        Italy
13      Denmark
14      Belgium
15  Philippines
16      Germany
17  Switzerland
18      Ireland

## == car world name bala customer ==

In [18]:
query = "SELECT DISTINCT CUSTOMERNAME FROM sales WHERE CUSTOMERNAME LIKE '%Car%';"
pd.read_sql(query, conn)

  CUSTOMERNAME
0  Mini Caravy