In [28]:
import numpy as np
import pandas as pd

In [29]:
date = pd.read_csv('orders.csv')
time = pd.read_csv('messages.csv')

In [30]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [31]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [32]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [33]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

# working with date

In [34]:
# converting to datetime datatype
date['date'] = pd.to_datetime(date['date'])

In [35]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.Extract year

In [36]:
date['date_year'] = date['date'].dt.year  #dt=datetime

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2. Extract month

In [37]:
date['date_month_no'] = date['date'].dt.month

date.head()

        date  product_id  city_id  orders  date_year  date_month_no
0 2019-12-10        5628       25       3       2019             12
1 2018-08-15        3646       14     157       2018              8
2 2018-10-23        1859       25       1       2018             10
3 2019-08-17        7292       25       1       2019              8
4 2019-01-06        4344       25       3       2019              1

## 3. month name

In [38]:
date['date_month_name'] = date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

## 4. extract day

date['date_day'] = date['date'].dt.day

date.head()

## 5. day of week

In [39]:
date['date_dow'] = date['date'].dt.dayofweek

date.head()

,date,product_id,city_id,orders,date_year,date_month_no,date_month_name,date_dow
0,2019-12-10,5628,25,3,2019,12,December,1
1,2018-08-15,3646,14,157,2018,8,August,2
2,2018-10-23,1859,25,1,2018,10,October,1
3,2019-08-17,7292,25,1,2019,8,August,5
4,2019-01-06,4344,25,3,2019,1,January,6

## 6. day of week - name

In [40]:
date['date_dow_name'] = date['date'].dt.day_name()
date.drop(columns=['product_id','city_id','orders']).head()

        date  date_year  date_month_no date_month_name  date_dow date_dow_name
0 2019-12-10       2019             12        December         1       Tuesday
1 2018-08-15       2018              8          August         2     Wednesday
2 2018-10-23       2018             10         October         1       Tuesday
3 2019-08-17       2019              8          August         5      Saturday
4 2019-01-06       2019              1         January         6        Sunday

## 7. is weekend

In [41]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday','Saturday']),1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,1,Tuesday,0
1,2018-08-15,2018,8,August,2,Wednesday,0
2,2018-10-23,2018,10,October,1,Tuesday,0
3,2019-08-17,2019,8,August,5,Saturday,1
4,2019-01-06,2019,1,January,6,Sunday,1

## 8. Extract week of the year

In [45]:
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,1,Tuesday,0,50
1,2018-08-15,2018,8,August,2,Wednesday,0,33
2,2018-10-23,2018,10,October,1,Tuesday,0,43
3,2019-08-17,2019,8,August,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,Sunday,1,1

## 9. extract quarter

In [46]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,Sunday,1,1,1

## 10. extract semester

In [51]:
date['semester'] = np.where(date['quarter'].isin([1,2]),1,2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,date_year,date_month_no,date_month_name,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,Sunday,1,1,1,1

##

## 11. extract time elapsed between dates

In [52]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 8, 5, 12, 54, 33, 140873)

In [53]:
today - date['date']

0     2430 days 12:54:33.140873
1     2912 days 12:54:33.140873
2     2843 days 12:54:33.140873
3     2545 days 12:54:33.140873
4     2768 days 12:54:33.140873
                 ...
995   2858 days 12:54:33.140873
996   2799 days 12:54:33.140873
997   2647 days 12:54:33.140873
998   2712 days 12:54:33.140873
999   2486 days 12:54:33.140873
Name: date, Length: 1000, dtype: timedelta64[ns]

In [55]:
(today - date['date']).dt.days

0      2430
1      2912
2      2843
3      2545
4      2768
       ...
995    2858
996    2799
997    2647
998    2712
999    2486
Name: date, Length: 1000, dtype: int64

In [61]:
# month passed

np.round((today - date['date']) / np.timedelta64(30, 'D'),0)

0      81.0
1      97.0
2      95.0
3      85.0
4      92.0
       ...
995    95.0
996    93.0
997    88.0
998    90.0
999    83.0
Name: date, Length: 1000, dtype: float64

# working with time

In [63]:
time

                    date                                                msg
0    2013-12-15 00:50:00                           ищу на сегодня мужика 37
1    2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2    2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3    2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4    2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше
..                   ...                                                ...
995  2012-03-16 00:50:00     ПАРЕНЬ СДЕЛАЕТ  МАССАЖ ЖЕНЩИНАМ -066-877-32-44
996  2014-01-23 23:14:00            сельский п 23 ищу девушку для отношений
997  2012-10-15 23:37:00  Д+Д ДЛЯ серьезных отношений. Мой номер 093-156...
998  2012-06-21 23:34:00  7 ДНЕПР М.34 ПОЗ.С Д/Ж ДЛЯ ВСТРЕЧ.Т.098 809 15 14
999  2014-06-19 23:25:00          Парень поласкает девушке...  т.0662035584

[1000 rows x 2 columns]

In [66]:
# converting to datetime datatype

time['date'] = pd.to_datetime(time['date'])

In [67]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [69]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

## 1. extract time part

In [70]:
time['time'] = time['date'].dt.time
time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

## 2. time difference

In [71]:
today - time['date']

0     4616 days 12:04:33.140873
1     4480 days 13:14:33.140873
2     4966 days 12:33:33.140873
3     4268 days 12:23:33.140873
4     4665 days 13:43:33.140873
                 ...
995   5255 days 12:04:33.140873
996   4576 days 13:40:33.140873
997   5041 days 13:17:33.140873
998   5157 days 13:20:33.140873
999   4429 days 13:29:33.140873
Name: date, Length: 1000, dtype: timedelta64[ns]

In [72]:
# in second
(today - time['date'])/np.timedelta64(1, 's')

0      3.988659e+08
1      3.871197e+08
2      4.291076e+08
3      3.687998e+08
4      4.031054e+08
           ...
995    4.540755e+08
996    3.954156e+08
997    4.355903e+08
998    4.456128e+08
999    3.827142e+08
Name: date, Length: 1000, dtype: float64