In [1]:
import sqlite3
import pandas as pd

In [2]:
conn = sqlite3.connect(':memory:')

In [3]:
# create table
conn.execute("""
CREATE TABLE sales (
    id INTEGER,
    product TEXT,
    category TEXT,
    amount INTEGER,
    city TEXT,
    sale_date TEXT
);
""")

In [4]:
conn.executemany("INSERT INTO sales VALUES (?,?,?,?,?,?)", [
    (1, 'Laptop', 'Electronics', 55000, 'Mumbai', '2024-01-05'),
    (2, 'Mouse', 'Electronics', 500, 'Mumbai', '2024-01-06'),
    (3, 'Shirt', 'Clothing', 1200, 'Delhi', '2024-01-07'),
    (4, 'Laptop', 'Electronics', 52000, 'Delhi', '2024-01-10'),
    (5, 'Jeans', 'Clothing', 2000, 'Mumbai', '2024-01-12'),
    (6, 'Mouse', 'Electronics', 450, 'Pune', '2024-01-15'),
    (7, 'Shirt', 'Clothing', 1100, 'Pune', '2024-01-18'),
])

In [8]:
conn.commit()
print('Table Ready')

Table Ready

query = "SELECT * FROM sales;"
pd.read_sql(query, conn)

# filtering

In [9]:
query = "SELECT * FROM sales WHERE city = 'Mumbai';"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   1  Laptop  Electronics   55000  Mumbai  2024-01-05
1   2   Mouse  Electronics     500  Mumbai  2024-01-06
2   5   Jeans     Clothing    2000  Mumbai  2024-01-12

In [10]:
query = "SELECT * FROM sales WHERE amount > 50000;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   1  Laptop  Electronics   55000  Mumbai  2024-01-05
1   4  Laptop  Electronics   52000   Delhi  2024-01-10

In [13]:
query = "SELECT * FROM sales WHERE product = 'Mouse';"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   2   Mouse  Electronics     500  Mumbai  2024-01-06
1   6   Mouse  Electronics     450    Pune  2024-01-15

# SORTING

## 1. bade se chote

In [17]:
query = "SELECT * FROM sales ORDER BY amount DESC;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   1  Laptop  Electronics   55000  Mumbai  2024-01-05
1   4  Laptop  Electronics   52000   Delhi  2024-01-10
2   5   Jeans     Clothing    2000  Mumbai  2024-01-12
3   3   Shirt     Clothing    1200   Delhi  2024-01-07
4   7   Shirt     Clothing    1100    Pune  2024-01-18
5   2   Mouse  Electronics     500  Mumbai  2024-01-06
6   6   Mouse  Electronics     450    Pune  2024-01-15

## 1. chote se bade

In [18]:
query = "SELECT * FROM sales ORDER BY amount;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   6   Mouse  Electronics     450    Pune  2024-01-15
1   2   Mouse  Electronics     500  Mumbai  2024-01-06
2   7   Shirt     Clothing    1100    Pune  2024-01-18
3   3   Shirt     Clothing    1200   Delhi  2024-01-07
4   5   Jeans     Clothing    2000  Mumbai  2024-01-12
5   4  Laptop  Electronics   52000   Delhi  2024-01-10
6   1  Laptop  Electronics   55000  Mumbai  2024-01-05

## 3. text columns se sort

In [19]:
query = "SELECT * FROM sales ORDER BY city;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   3   Shirt     Clothing    1200   Delhi  2024-01-07
1   4  Laptop  Electronics   52000   Delhi  2024-01-10
2   1  Laptop  Electronics   55000  Mumbai  2024-01-05
3   2   Mouse  Electronics     500  Mumbai  2024-01-06
4   5   Jeans     Clothing    2000  Mumbai  2024-01-12
5   6   Mouse  Electronics     450    Pune  2024-01-15
6   7   Shirt     Clothing    1100    Pune  2024-01-18

In [20]:
query = "SELECT * FROM sales ORDER BY category;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   3   Shirt     Clothing    1200   Delhi  2024-01-07
1   5   Jeans     Clothing    2000  Mumbai  2024-01-12
2   7   Shirt     Clothing    1100    Pune  2024-01-18
3   1  Laptop  Electronics   55000  Mumbai  2024-01-05
4   2   Mouse  Electronics     500  Mumbai  2024-01-06
5   4  Laptop  Electronics   52000   Delhi  2024-01-10
6   6   Mouse  Electronics     450    Pune  2024-01-15

In [22]:
query = "SELECT * FROM sales ORDER BY product;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   5   Jeans     Clothing    2000  Mumbai  2024-01-12
1   1  Laptop  Electronics   55000  Mumbai  2024-01-05
2   4  Laptop  Electronics   52000   Delhi  2024-01-10
3   2   Mouse  Electronics     500  Mumbai  2024-01-06
4   6   Mouse  Electronics     450    Pune  2024-01-15
5   3   Shirt     Clothing    1200   Delhi  2024-01-07
6   7   Shirt     Clothing    1100    Pune  2024-01-18

## 4. do cloumns se sorting

In [25]:
query = "SELECT * FROM sales ORDER BY category, amount;"
pd.read_sql(query, conn)

   id product     category  amount    city   sale_date
0   7   Shirt     Clothing    1100    Pune  2024-01-18
1   3   Shirt     Clothing    1200   Delhi  2024-01-07
2   5   Jeans     Clothing    2000  Mumbai  2024-01-12
3   6   Mouse  Electronics     450    Pune  2024-01-15
4   2   Mouse  Electronics     500  Mumbai  2024-01-06
5   4  Laptop  Electronics   52000   Delhi  2024-01-10
6   1  Laptop  Electronics   55000  Mumbai  2024-01-05

## 5. group by ke result ko sort karna

In [27]:
query = "SELECT category, SUM(amount) AS total_amount FROM sales GROUP BY category ORDER BY total_amount DESC;"
pd.read_sql(query, conn)

      category  total_amount
0  Electronics        107950
1     Clothing          4300

# HAR CITY KA TOTAL SALES

In [29]:
query = "SELECT city, SUM(amount) AS total_amount FROM sales GROUP BY city"
pd.read_sql(query, conn)

     city  total_amount
0   Delhi         53200
1  Mumbai         57500
2    Pune          1550

# HAR PRODUCT KA AVERAGE AMOUNT

In [30]:
query = "SELECT product, AVG(amount) AS total_amount FROM sales GROUP BY product"
pd.read_sql(query, conn)

  product  total_amount
0   Jeans        2000.0
1  Laptop       53500.0
2   Mouse         475.0
3   Shirt        1150.0

# HAR COTEGORY KE TOTAL ORDER, HIGHEST SE LOWEST

In [32]:
query = "SELECT category, COUNT(*) AS total_orders FROM sales GROUP BY category ORDER BY total_orders DESC;"
pd.read_sql(query, conn)

      category  total_orders
0  Electronics             4
1     Clothing             3

# HAR CITY MAIN SABSE BADI SINGLE SALE

In [35]:
query = "SELECT city, MAX(amount) AS max_sale FROM sales GROUP BY city"
pd.read_sql(query, conn)

     city  max_sale
0   Delhi     52000
1  Mumbai     55000
2    Pune      1100

# CATEGORY JINKA TOTAL 1500 SE JYADA HAI

In [38]:
query = "SELECT category, SUM(amount) AS total_amount FROM sales GROUP BY category HAVING SUM(amount) > 1500 DESC;"
pd.read_sql(query, conn)

DatabaseError: Execution failed on sql 'SELECT category, SUM(amount) AS total_amount FROM sales GROUP BY category HAVING SUM(amount) > 1500 DESC;': near "DESC": syntax error