In [73]:
import numpy as np 
import pandas as pd

from sklearn.linear_model import LinearRegression

In [74]:
df = np.round(pd.read_csv('50_Startups.csv')[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)

In [75]:
np.random.seed(9)

In [76]:
df = df.sample(5)

In [77]:
df

    R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [78]:
df = df.iloc[:,0:3].copy()
df

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [79]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[4,2] = np.nan

In [80]:
df.head()

    R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [81]:
# step 1 - Impute all missing values withmean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Administration'].mean())

In [82]:
df0

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            11.25

## remove the col 1 impute values

In [127]:

df1 = df0.copy()
df1.iloc[1,0] = np.nan
df1

    R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            11.25

In [128]:
# use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

    Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            11.25

In [129]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [130]:
lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

array([16.35889241])

In [131]:
df1.iloc[1,0] = 16.35

In [132]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      16.35            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            11.25

## remove the col 2 impute values

In [133]:
df1.iloc[3,1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      16.35             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            11.25

In [134]:
# use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

    R&D Spend  Marketing Spend
21       8.00            30.00
37      16.35            20.00
2       15.00            41.00
44       2.00            11.25

In [135]:
y = df.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [136]:
lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

array([9.90287508])

In [137]:
df1.iloc[3,1] =9.90
df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      16.35             5.0            20.00
2       15.00            10.0            41.00
14      12.00             9.9            26.00
44       2.00            15.0            11.25

## remove the col 3 impute value

In [138]:
df1.iloc[4,-1] = np.nan

df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0             30.0
37      16.35             5.0             20.0
2       15.00            10.0             41.0
14      12.00             9.9             26.0
44       2.00            15.0              NaN

In [139]:
# use last 3 rows to build a model ans use for prediction

X = df1.iloc[0:4,0:2]
X

    R&D Spend  Administration
21       8.00            15.0
37      16.35             5.0
2       15.00            10.0
14      12.00             9.9

In [140]:
y = df1.iloc[0:4,-1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [141]:
lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

array([-0.96279304])

In [143]:
df1.iloc[4,-1] = -0.96

In [144]:
df1

    R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      16.35             5.0            20.00
2       15.00            10.0            41.00
14      12.00             9.9            26.00
44       2.00            15.0            -0.96

## Substraction 0th iteration from 1st iteration

In [145]:
df1 - df0

    R&D Spend  Administration  Marketing Spend
21        0.0            0.00             0.00
37        7.1            0.00             0.00
2         0.0            0.00             0.00
14        0.0           -1.35             0.00
44        0.0            0.00           -12.21

In [167]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

In [178]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

In [179]:
lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

array([14.91676157])

In [180]:
df2.iloc[1,0] = 15.52

In [181]:
df2.iloc[3,1] = np.nan

In [182]:
X = df2.iloc[[0,2,4],[0,2]]
y = df2.iloc[[0,2,4],[1]]

lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

array([[10.08982036]])

In [183]:
df2.iloc[3,1] = 10.09

In [184]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[[0,2,3],0:2]
y = df2.iloc[[0,2,3],-1]

lr = LinearRegression()
lr.fit(X.values,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

array([-0.90187891])

In [185]:
df2.iloc[4,-1] = -0.90

In [186]:
df2

    R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      15.52            5.00            15.52
2       15.00           10.00            41.00
14      12.00           10.09            26.00
44       2.00           15.00            -0.90